
apiVersion: v1
kind: Service
metadata:
 name: myservice
 labels:
  app: myservicetesting
spec:
 selector:
  env: testing
 type: NodePort
 ports:
  - name: port1
    port: 9090
    targetPort: 9090
  - name: port2
    port: 3000
    targetPort: 3000 